runtime:
  language: python
  version: "3.11"

setup:
  - run: python -m venv .venv
  - run: .venv/bin/pip install --upgrade pip
  - run: .venv/bin/pip install requests

tasks:
  test:
    run: .venv/bin/python -c "import requests; print('✅ requests installed OK')"
